### ISSUE TITLE
UpdateRange?

### ISSUE THREAD

**Issue by pboisso** [jamesmontemagno/mvvm-helpers#10]
First, thanks for the nice ObservableCollection class.  Very convenient !

I was wondering if you could consider adding an "UpdateRange" and/or "AddAndUpdateRange" method where the collection passed would update any items in the collection if they already exists in it?

We have implemented something like this, but if you could add it to the package, this might be a nice addition.  Would not mind a code review also if not. ;)

What are your thoughts?

       public void UpdateRange(IEnumerable<T> collection, Predicate<T> match, bool InsertOnUpdate = true)
        {
            if (collection == null)
                throw new ArgumentNullException("collection");

                CheckReentrancy();

                var oldItems = new List<T>();
                var updatedItems = new List<T>();
                var newItems = new List<T>();

                int startIndex = this.Count;
                var changedItems = collection is List<T> ? (List<T>) collection : new List<T>(collection);
                foreach (var item in changedItems)
                {
                    var updated = item;
                    var index = ((List<T>) this.Items).FindIndex(match);  //using a Predicate is allowing us to pass the way we want to compare the items, for example, our objects all have a Key property what we want to compare with, so we pass match = o => o.Key == updated.Key

                    if (index > -1)
                    {
                        oldItems.Add(this.Items[index]);
                        this.Items[index] = updated;
                        updatedItems.Add(updated);
                    }
                    else
                    {
                        if (InsertOnUpdate)
                        {
                            // There are some situation when we do NOT want to insert new items, we just want to update if they are present in the collection.
                            this.Items.Add(updated);
                            newItems.Add(updated);
                        }
                    }

                if (newItems.Count > 0)
                {
                    OnPropertyChanged(new PropertyChangedEventArgs("Count"));
                    OnPropertyChanged(new PropertyChangedEventArgs("Item[]"));  //for all indexes
                                                                                //todo, do this for each index? OnPropertyChanged(new PropertyChangedEventArgs("Item[" + index + "]"));  //for a single item
                    OnCollectionChanged(new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Add, newItems.ToArray(), startIndex));
                }

                if (oldItems.Count > 0)
                {
                    if (!(newItems.Count > 0))  //already notified above otherwise
                        OnPropertyChanged(new PropertyChangedEventArgs("Item[]"));  //for all indexes
                                                                                    //todo, do this for each index? OnPropertyChanged(new PropertyChangedEventArgs("Item[" + index + "]"));  //for a single item
                    OnCollectionChanged(new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Replace, oldItems.ToArray(), updatedItems.ToArray()));
                }
            }
        }

**Comment by jamesmontemagno** [comment]
I think ReplaceRange would handle this?

**Comment by jamesmontemagno** [comment]
Ah, i see these are different, haven't thought about it yet.

**Comment by RichiCoder1** [comment]
I've actually implemented this twice. Very helpful for efficiently updating lists.
