### ISSUE TITLE
Concurrent collection?

### ISSUE THREAD

**Issue by pboisso** [jamesmontemagno/mvvm-helpers#11]
Hi again,

Our ObservableCollection is being updated on background threads from real-time pub-sub connections and it happens (rarely) in some cases that we get 'The collection has changed' type error when (I guess), there are another update that comes trough before the UI has completed its update.

I was wondering if there were any plan to make ObservableCollection thread-safe (ConcurrentObservableCollection?)

Thanks again for the contribution, really appreciate.

**Comment by jamesmontemagno** [comment]
I would have to think about it, most likely you would need to pass some function into it and have it invoke on the desired UI thread.

You just need to invoke the action currently on the UI thread for updating. Or use a standard List really if you need to manually trigger UI updates

**Comment by jamesmontemagno** [comment]
I have decided out of scope of what I am comfortable implementing and having to maintain in this library.
