### ISSUE TITLE
Adding IValueConverters?

### ISSUE THREAD

**Issue by Chrisgozd** [jamesmontemagno/mvvm-helpers#13]
Would you want to add some common IValueConverters to this library, such as InverseBooleanConverter? Or does it not fit in this particular library?  

If you want them, I can open a PR with it.

**Comment by jamesmontemagno** [comment]
IValueConverters are platform specific so I can't put them here. Take a look at this: https://github.com/FormsCommunityToolkit/FormsCommunityToolkit
