### ISSUE TITLE
.NET Standard compatibility?

### ISSUE THREAD

**Issue by zuckerthoben** [jamesmontemagno/mvvm-helpers#19]
I just started building a new XF solution (iOS, Android, UWP). It's my first solution with .Net Standard 1.4. I tried adding MvvmHelpers but I always get errors when building. 

> Severity	Code	Description	Project	File	Line	Suppression State
> Error		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'MvvmHelpers, Version=1.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
> File name: 'MvvmHelpers.dll'
>    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
>    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference)
>    at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
>    at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	Roomplan.Android			
 
I tried cleaning (+ deleting bin&obj folders) and rebuilding, without success. Is the library not ready for Standard or is something wrong on my end? 

Greetings and thank you for the work.

**Comment by jamesmontemagno** [comment]
Do you have a project that I could look at?

It is currently a .net standard 1.0 library and seems to work for me just fine.

**Comment by zuckerthoben** [comment]
There you go. https://1drv.ms/u/s!AvJLub4840pXq7ZQ0v5bD4i86570vQ 
Cant put it on GitHub, since it's code for work :) 

The error goes away when I download the MVVMHelpers solution and put it in my solution as a direct reference instead of NuGet or add the NuGet to the Android project. But then I get the same error for Newtonsoft.JSON. And then for Portable Data Annotations. I basically have to add all references that are already in the PCL to the Android project to get it to work. That was never the case and is surely not intentional.

**Comment by jamesmontemagno** [comment]
Didn't have any issue here on it: 
![image](https://cloud.githubusercontent.com/assets/1676321/26685867/4b349b06-46b9-11e7-8646-becdd34e5b0e.png)

I am on the latest VS 2017 version 15.2.2

**Comment by jamesmontemagno** [comment]
Can you tell me what NuGet is saying?

**Comment by jamesmontemagno** [comment]
Going to close as I can't reproduce

**Comment by zuckerthoben** [comment]
I managed to solve the issue by recreating the solution and enabling .NET Standard once again and a little different. Thank you for your time, I appreciate it :)
