### ISSUE TITLE
Use ObservableRangeCollection as ring-buffer

### ISSUE THREAD

**Issue by abrasat** [jamesmontemagno/mvvm-helpers#24]
Would be possible to extend the functionality for the ObservableRangeCollection to support the implementation of a ring-buffer ?
For instance a new "AddRangeAdjustToMaxCapacity()" method, that checks if the range of items to be added would exceed the ObservableRangeCollection capacity, and remove the neccesary amount of items from the collection, before adding the new ones. I know that this could be reached by calling RemoveRange and after that AddRange, but would be much better to have it in a single call. Of course, an additional ObservableRangeCollection(int capacity) constructor would also be needed, to be able to set the max. capacity of the collection

**Comment by jamesmontemagno** [comment]
You can fork the repo, i don't plan on pulling in many changes. you may just want to think of building an extension method for yourself.
