### ISSUE TITLE
Q : How to update particular property of BindableObject without again using SetProperty

### ISSUE THREAD

**Issue by avinashramireddy-rapidd** [jamesmontemagno/mvvm-helpers#28]
Hi James,

Today I came with some situation where I need to update only one property of class object(this is set using SetProperty method) 
```

 private ProfileSettings profileSettings;
 public ProfileSettings ProfileSettings
  {
     get { return profileSettings; }
     set { SetProperty(ref profileSettings, value); }
  } 
 ```

here is my ProfileSettings  class used for binding
```

 public class ProfileSettings : BaseViewModel
 {
   public string Country { get; set; } 

  //some other properties like timezone,dateformat etc...
 }
```

Now when I click on country label in my ProfileSettingsPage it takes me to listview where I select particular country from list provided and when I comeback(Ondisappearing) I am passing this country item back to ProfileSettingPage using messaging center with selectedItem as parameter(TArgs).

**Problem** 
If I don't make the Country bindable inside ProfileSettings class like below,it's not updating my label  on page.
``` 
    private string country;  

    [JsonProperty("cntry")]
    public string Country
    {
      get { return country; }
      set { SetProperty(ref country, value); }
     }  
```
It's same for all other properties in my ProfileSettings class.

**Question:** Is there any way to make all the properties inside class bindable automatically... Or Am I doing something wrong with approach?

**Comment by jamesmontemagno** [comment]
You need to raise property changes on the child. So looks like you already found the solution of setproperty on the country property, which is correct.
