### ISSUE TITLE
Please change the ObservableObject.OnChangeProperty and SetProperty to Virtual on Nuget.

### ISSUE THREAD

**Issue by maxchu92** [jamesmontemagno/mvvm-helpers#31]
MVVM helpers is such an easy to use package! But i did like to have some customization.
I understand that i can download the source code and compile a customized version for myself.
Changing the modifier allows users that uses the NuGet directly able to customize themselves.
If its possible, please change the ObservableObject.OnChangeProperty and SetProperty on the NuGet to Virtual to enable overrides.

Thank you.

**Comment by jamesmontemagno** [comment]
They already are: 
![image](https://user-images.githubusercontent.com/1676321/35827762-1af27832-0a72-11e8-98bc-828ee88a922e.png)

**Comment by maxchu92** [comment]
I am using the latest version of MvvmHelpers v1.3.0 on NuGet.
![image](https://user-images.githubusercontent.com/4240515/35953295-e0918cd8-0cbe-11e8-849e-a97714f59e79.png)
![image](https://user-images.githubusercontent.com/4240515/35953291-dc741d32-0cbe-11e8-8d07-472bdb93ad74.png)

**Comment by jamesmontemagno** [comment]
You will need to use the pre-release that has it. I am working on bundling up 1.4.0 though soon which will have it.

**Comment by maxchu92** [comment]
Oh. Sure! Thank you!

**Comment by CZEMacLeod** [comment]
@jamesmontemagno Any progress on the 1.4.0 release? I've switched to the pre-release for this same issue.
