### ISSUE TITLE
Not practical for models that already derives from another types

### ISSUE THREAD

**Issue by AdhamAliAhmed** [jamesmontemagno/mvvm-helpers#34]
In our models instead of deriving from INotifyProperty changed, we derive from ObservableObject. So in many cases where we have models that already derives from another classes, this wont help.
For instance in my models i have class called Tournament that derives from IGrouping because i have another types like Group and Match that shares a lot of functionality. How would i derive from Observable object?

**Comment by jamesmontemagno** [comment]
You can have classes that inherit from a class and also implement an interface:

```csharp
public class MyClass: ObservableObject, IGrouping
{
}
```
