### ISSUE TITLE
'Title' iOS iPhoneSimulator versus iPhone device not appearing 

### ISSUE THREAD

**Issue by jimwallery** [jamesmontemagno/mvvm-helpers#36]
I am working on a sandbox xamarin.forms.map application using databinding(pedley to create bindable objects) and custom renderers(to make pins and locations similar among devices) and using mvvm-helpers nuget package to create observablerangecollections, geolocation (ala Monkey6000 app). 

When I deploy the application to the iOS target on the iPhoneSimulator I get the 'Title' appearing.

When I deploy the application to the iOS target on the iPhone device I do not get the 'Title' appearing.

I have tried on a couple different iOS deployment targets 9.3 and 11.0.  Maybe I'm missing something in the iOS deployment to the iPhone?  Any suggestion is much appreciated.  Thank you.

**Comment by jamesmontemagno** [comment]
I would need a sample please.
