### ISSUE TITLE
ObservableRangeCollection<T>.ReplaceRange not recognized by Xamarin.Forms CollectionView

### ISSUE THREAD

**Issue by xamadev** [jamesmontemagno/mvvm-helpers#39]
Got a Xamarin.Forms CollectionView whose ItemsSource is an ObservableRangeCollection<T>. Items are loaded asynchronously at page appearing. The ViewModel replaces existing items and adds new items to the collection by calling the ReplaceRange. The CollectionView somehow doesn't notice data change and nothing is displayed. Applying one of the following changes does show the items.

Workaround 1: Call ObservableRangeCollection<T>.Clear and afterwards ObservableRangeCollection<T>.AddRange

Workaround 2: Use ObservableCollection<T>, call Clear and add items in a foreach loop using the Add method.

Reproduction Link:
https://github.com/xamadev/ObservableRangeCollectionError
Tested on iPhone simulator only

Thanks to @jamesmontemagno for the great helperclasses!

**Comment by jamesmontemagno** [comment]
I would file a bug on Xamarin.Forms as it probably doesn't respect the Reset command.

**Comment by adrianknight89** [comment]
Not sure if `CollectionView` supports `ObservableRangeCollection`.

https://github.com/jamesmontemagno/mvvm-helpers
https://gist.github.com/weitzhandler/65ac9113e31d12e697cb58cd92601091
https://forums.xamarin.com/discussion/29925/observablecollection-addrange

Looks like there is an internal [`ObservableList<T>`](https://github.com/xamarin/Xamarin.Forms/blob/bd31e1e9fc8b2f9ad94cc99e0c7ab058174821f3/Xamarin.Forms.Core/ObservableList.cs) with similar functionality.

**Comment by pfedotovsky** [comment]
Both workarounds doesn't work for me - I get

`Objective - C exception thrown.  Name: NSInternalInconsistencyException Reason: Invalid update: invalid number of items in section 0.The number of items contained in an existing section after the update(13) must be equal to the number of items contained in that section before the update(13), plus or minus the number of items inserted or deleted from that section (13 inserted, 0 deleted) and plus or minus the number of items moved into or out of that section(0 moved in, 0 moved out).`

Any ideas how to fix it?
