### ISSUE TITLE
SetProperty Usage

### ISSUE THREAD

**Issue by Orgbrat** [jamesmontemagno/mvvm-helpers#40]
So is there a Xamarin Forms example of using the mvvm-helpers SetProperty with all parameters. How to do you take advantage of the Action and validate parameters from a model or viewmodel where model inherits from ObservableObject and viewmodel inherits from BaseViewModel with MVVM pattern?

Orgbrat

**Comment by jamesmontemagno** [comment]
Sure, you could take  look at our samples for xamarin.essentials: https://github.com/xamarin/Essentials/tree/master/Samples/Samples/ViewModel
