### ISSUE TITLE
Latest stable NuGet package is over 2.5 years old

### ISSUE THREAD

**Issue by nwilliams** [jamesmontemagno/mvvm-helpers#60]
I'm moving away from my go-to MVVM framework due to compatibility issues with Shell and came across your MvvmHelpers library. I would very much like to leverage many of the features you've added in recent years, but all of the packages you've published since v1.3 have been in beta. Are there specific concerns that have prevented you from publishing recent releases as stable?

**Comment by jamesmontemagno** [comment]
Nope, just been testing it out. Stable is extremely stable. there are no breaking changes, but I would recommend testing the beta out :)
