### ISSUE TITLE
raise ObservableRangeCollection on item propertychanged

### ISSUE THREAD

**Issue by shakazulu89** [jamesmontemagno/mvvm-helpers#63]
hey all
maybe im missing something stupid and im sure its been asked before but for some reason cant find my answer:
if i have a ObservableRangeCollection<MyItem> and a property in MyItem changes (MyItem is an observableobject), how do i get the observablecollection to notice the change?

**Comment by jamesmontemagno** [comment]
The collection would not have changed the item inside of it would have. So you need to implement INotifyPropertyChanged on your "MyItem"

**Comment by shakazulu89** [comment]
thanks james for taking the time to answer. i got it to work. just felt like i was missing something built into mvvmhelpers :P
