### ISSUE TITLE
.net core 3.0 end of life

### ISSUE THREAD

**Issue by lsaudon** [jamesmontemagno/mvvm-helpers#64]
This release has reached end of life, meaning it is no longer supported. 
We recommend moving to a supported release.

**Comment by jamesmontemagno** [comment]
Mvvm Helpers is just a .net standard library so can be used anywhere.

I think some of my tests are on older versions, but all the same, can update them if that is what you mean?

**Comment by lsaudon** [comment]
Sorry for the lack of precision. 
The project [MvvmHelpers.UnitTests.csproj](https://github.com/jamesmontemagno/mvvm-helpers/blob/master/MvvmHelpers.UnitTests/MvvmHelpers.UnitTests.csproj) is in .net core 3.0.
