### ISSUE TITLE
Update from 1.5.0-beta to 1.6.2 on SafeFireAndForgetAsync

### ISSUE THREAD

**Issue by ThanawutZiios** [jamesmontemagno/mvvm-helpers#66]
Hi,

Now I'm using 1.5.0-beta and use Utils.SafeFireAndForgetAsync a lot on the code.
but when I try to update to 1.6.2 that method are gone.

So you do not support that anymore or you change method name?

Thank you,
Thanawut

**Comment by jamesmontemagno** [comment]
I don't think I ever removed them.

https://github.com/jamesmontemagno/mvvm-helpers/blob/master/MvvmHelpers/Utils.cs#L47

It is just SafeFireAndForget
