### ISSUE TITLE
Any helper classes/methods for handling navigation in MVVM ?

### ISSUE THREAD

**Issue by ampslive** [jamesmontemagno/mvvm-helpers#7]
Can you provide any boiler plate MVVM classes/methods that can help make navigation simpler in MVVM.

**Comment by jamesmontemagno** [comment]
This helpers class doesn't rely on any framework at all and can be used in Xamarin traditional or xamarin.forms so there are no navigation helpers. May want to look into Prism for Xamarin.Forms
