### ISSUE TITLE
Task<T>.WithTimeout() TimeSpan overload should use TotalMilliseconds instead of Milliseconds

### ISSUE THREAD

**Issue by AdamDotNet** [jamesmontemagno/mvvm-helpers#8]
https://github.com/jamesmontemagno/mvvm-helpers/blob/master/MvvmHelpers/Utils.cs

`TimeSpan.TotalMilliseconds` converts the entire `TimeSpan` to milliseconds, whereas `TimeSpan.Milliseconds` simply returns the milliseconds portion of the timespan. If I wanted to timeout in 10 seconds, and used

`Task task; //...`
`await task.WithTimeout(TimeSpan.FromSeconds(10));`

I would get a timeout of 0 milliseconds instead of 10000 milliseconds.

**Comment by jamesmontemagno** [comment]
Fixed. Thanks
