### ISSUE TITLE
WPF issue -> no disabling of buttons using MvvmHelper commands

### ISSUE THREAD

**Issue by trondr** [jamesmontemagno/mvvm-helpers#86]
When binding a button to a MvvmHelper command, the button is not disabled when canExecute is returning false. It seems canExecute is not called or triggered by the MvvmHelper commands? The command implementation in MvvmLight library and  "another" AsyncCommand implementation is working just fine. if the error is in my code I do not spot it. Please advice.

![image](https://user-images.githubusercontent.com/2294892/113456637-0e948700-940e-11eb-8253-ff03297a43ab.png)

Attached is a example project reproducing the issue.
[WpfApp1.zip](https://github.com/jamesmontemagno/mvvm-helpers/files/6251387/WpfApp1.zip)

Package used: Refractored.MvvmHelpers 1.6.2

**Comment by jamesmontemagno** [comment]
My commands are generic and do not loop into the CommandManager, so you must raise events manually.

You would need to add:
```
 public new bool IsBusy
        {
            get => base.IsBusy;
            set
            {
                base.IsBusy = value;
                _clickMeMvvmHelpersAsyncCommand.RaiseCanExecuteChanged();
                _clickMeMvvmHelpersCommand.RaiseCanExecuteChanged();
            }
        }
```

**Comment by trondr** [comment]
Thanks for the quick response! I see. Probably no other way around it when the library is generic. Even if one of the reasons for using helper classes is to avoid the manual raising of events. An alternative I am thinking about is to keep a copy of the source code in the WPF project and change the following in AsyncCommand.cs and Command.cs from:
```CSharp
/// <summary>
/// Event handler raised when CanExecute changes.
/// </summary>
public event EventHandler CanExecuteChanged
{
	add { weakEventManager.AddEventHandler(value); }
	remove { weakEventManager.RemoveEventHandler(value); }
}
```
to: 
```CSharp
/// <summary>
/// Event triggered when Can Execute changes.
/// </summary>
public event EventHandler CanExecuteChanged
{
	add
	{
		weakEventManager.AddEventHandler(value);
		CommandManager.RequerySuggested += value;
	}
	remove
	{
		weakEventManager.RemoveEventHandler(value);
		CommandManager.RequerySuggested -= value;
	}
}
```
The reason for having to copy the source code is obviously due to the EventHandler class used by CommandManager is defined in mscorlib and the EventHandler class used by MvvmHelpers is defined in .NET Standard. Also to make my WPF .NET 4.7.2 project use the latest C# version, the following has to be defined in the WPF project file:

```XML
<LangVersion>latest</LangVersion>
````

I will think about it. Again thanks!
