### ISSUE TITLE
Explanatory Video not found 404

### ISSUE THREAD

**Issue by mvidaldev** [jamesmontemagno/mvvm-helpers#90]
Hello, there is an error when trying to access the video from "get started"  at link https://learn.microsoft.com/pt-br/shows/xamarinshow/the-xamarin-show-12-mvvm-helpers?wt.mc_id=friends-0000-jamont

**Comment by jamesmontemagno** [comment]
See: https://www.youtube.com/watch?v=y8ZqEOLDeo8
