### ISSUE TITLE
Strong Assembly name for MVVM - helpers

### ISSUE THREAD

**Issue by raajavel87** [jamesmontemagno/mvvm-helpers#91]
Hi there,

we tried to include the MVVM helpers reference in our project and we used strong naming for all other internal project modules Due to this we faced issues in building the project since MVVM helpers don't have strong naming for assemblies. Please give some solution for this issue.

Thanks,
Rajavel.K

**Comment by jamesmontemagno** [comment]
You could look at https://www.nuget.org/packages/StrongNamer

There is really no reason to strong name anymore.

**Comment by raajavel87** [comment]
> You could look at https://www.nuget.org/packages/StrongNamer
> 
> There is really no reason to strong name anymore.

Please mention the steps to be followed, I have added a reference to StrongName Nuget Packages and facing the same issue
