### ISSUE TITLE
Maui Support

### ISSUE THREAD

**Issue by pboisso** [jamesmontemagno/mvvm-helpers#92]
Hi,

We have been using this library in our Xamarin Forms app for years with success.

I've see that Xamaxin was supporting range collections, but that .Net Core might not.  How about Maui?

Is it safe to use this ObservableRangeCollection in Maui?  We are completing migration process, but still see some random crashes here and there and it's always during modification of the collection.

Thanks.
P

**Comment by jamesmontemagno** [comment]
Should work just fine, haven't seen any issues
